import type { Theme, ThemeName } from './types';

export const THEMES: Theme[] = [
	{
		name: 'glass-light',
		label: 'Verre Clair',
		bg: 'bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100',
		sidebar: 'bg-white/10 backdrop-blur-xl border-r border-white/60 shadow-xl',
		header: 'bg-white/10 backdrop-blur-xl border-b border-white/60 shadow-sm',
		card: 'bg-white/30 backdrop-blur-md border border-white/70 shadow-lg',
		cardHover: 'hover:bg-gray/100 hover:shadow-xl',
		primary: 'bg-indigo-600',
		primaryText: 'text-indigo-600',
		accent: 'bg-indigo-50',
		text: 'text-gray-800',
		textMuted: 'text-gray-800',
		border: 'border-white/60',
		badge: 'bg-indigo-100 text-indigo-700',
		icon: 'text-indigo-600',
	},
	{
		name: 'glass-dark',
		label: 'Verre Sombre',
		bg: 'bg-gradient-to-br from-slate-900 via-slate-950 to-gray-800',
		sidebar: 'bg-[#000000] backdrop-blur-xl border-r border-gray-700/50 shadow-xl',
		header: 'bg-[#000000] backdrop-blur-xl border-b border-gray-700/50 shadow-sm',
		card: 'bg-white-30 backdrop-blur-md border border-gray-700/50 shadow-lg',
		cardHover: 'hover:bg-zinc-900/50 hover:shadow-xl',
		primary: 'bg-blue-500',
		primaryText: 'text-blue-600',
		accent: 'bg-blue-900/30',
		text: 'text-gray-100',
		textMuted: 'text-gray-400',
		border: 'border-gray-700/50',
		badge: 'bg-blue-900/50 text-blue-300',
		icon: 'text-blue-400',
	},
	{
		name: 'glass-blue',
		label: 'Verre bleu foncé',
		bg: 'bg-gradient-to-br from-[#010B40] via-gray-700 to-[#010B40]',
		sidebar: 'bg-[#010626] backdrop-blur-xl border-r border-gray-700/50 shadow-xl',
		header: 'bg-[#010626] backdrop-blur-xl border-b border-gray-700/50 shadow-sm',
		card: 'bg-[#010626] backdrop-blur-md border border-gray-700/50 shadow-lg',
		cardHover: 'hover:bg-[#000000] hover:shadow-xl',
		primary: 'bg-blue-500',
		primaryText: 'text-blue-600',
		accent: 'bg-blue-900/30',
		text: 'text-gray-100',
		textMuted: 'text-gray-400',
		border: 'border-gray-700/50',
		badge: 'bg-blue-900/50 text-blue-300',
		icon: 'text-blue-400',
	},
	{
		name: 'ocean',
		label: 'Océan',
		bg: 'bg-gradient-to-br from-blue-400 via-[#023059] to-[#021373]',
		sidebar: 'bg-[#0477BF] backdrop-blur-xl border-r border-cyan-700/40 shadow-xl',
		header: 'bg-blue/20 backdrop-blur-xl border-b border-cyan-700/40 shadow-sm',
		card: 'bg-white/20 backdrop-blur-md border border-cyan-200/60 shadow-lg',
		cardHover: 'hover:bg-white/70 hover:shadow-xl',
		primary: 'bg-cyan-600',
		primaryText: 'text-cyan-700',
		accent: 'bg-cyan-50',
		text: 'text-black-800',
		textMuted: 'text-black-800',
		border: 'border-cyan-200/60',
		badge: 'bg-cyan-100 text-cyan-700',
		icon: 'text-cyan-600',
	},
	{
		name: 'purple',
		label: 'Violet Cosmos',
		bg: 'bg-gradient-to-br from-[#BC96E6] via-[#BC96E6] to-[#8A7ED9]',
		sidebar: 'bg-violet-900/80 backdrop-blur-xl border-r border-violet-700/40 shadow-xl',
		header: 'bg-violet/20 backdrop-blur-xl border-b border-violet-700/40 shadow-sm',
		card: 'bg-white/20 backdrop-blur-md border border-violet-200/60 shadow-lg',
		cardHover: 'hover:bg-white/70 hover:shadow-xl',
		primary: 'bg-violet-600',
		primaryText: 'text-violet-700',
		accent: 'bg-violet-50',
		text: 'text-black',
		textMuted: 'text-black',
		border: 'border-violet-200/60',
		badge: 'bg-violet-100 text-violet-700',
		icon: 'text-violet-600',
	},
	{
		name: 'emerald',
		label: 'Émeraude',
		bg: 'bg-gradient-to-br from-emerald-90 via-[#06BFBF] to-[#03B5AA]',
		sidebar: 'bg-emerald-900 backdrop-blur-xl border-r border-emerald-700/40 shadow-xl',
		header: 'bg-emerald/70 backdrop-blur-xl border-b border-emerald-700/40 shadow-sm',
		card: 'bg-white/20 backdrop-blur-md border border-emerald-200/60 shadow-lg',
		cardHover: 'hover:bg-white/70 hover:shadow-xl',
		primary: 'bg-emerald-600',
		primaryText: 'text-emerald-700',
		accent: 'bg-emerald-50',
		text: 'text-black-800',
		textMuted: 'text-black-800',
		border: 'border-emerald-200/60',
		badge: 'bg-emerald-100 text-emerald-700',
		icon: 'text-emerald-600',
	},
	{
		name: 'sunset',
		label: 'Coucher de Soleil',
		bg: 'bg-gradient-to-br from-orange-50 via-[#D98032] to-rose-100',
		sidebar: 'bg-[#8C4F04] backdrop-blur-xl border-r border-orange-700/40 shadow-xl',
		header: 'bg-orange/50 backdrop-blur-xl border-b border-orange-700/40 shadow-sm',
		card: 'bg-white/20 backdrop-blur-md border border-orange-200/60 shadow-lg',
		cardHover: 'hover:bg-white/70 hover:shadow-xl',
		primary: 'bg-orange-600',
		primaryText: 'text-orange-700',
		accent: 'bg-orange-50',
		text: 'text-black-800',
		textMuted: 'text-black-500',
		border: 'border-orange-200/60',
		badge: 'bg-orange-100 text-orange-700',
		icon: 'text-orange-600',
	},
];

export function getTheme(name: ThemeName | string): Theme {
	return THEMES.find(t => t.name === name) || THEMES[0];
}
